sonar.projectKey=davi-carlos_prova02-integration-tests-jest-master-Davi-Carlos
sonar.organization=davi-carlos
sonar.projectName=prova02-integration-tests-jest-master-Davi-Carlos
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**,**/output/**