sonar.projectKey=davi-carlos_prova02-integration-tests-jest-master-Davi-Carlos
sonar.organization=davi-carlos
sonar.projectName=prova02-integration-tests-jest-master-Davi-Carlos
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=test

sonar.test.inclusions=test/**/*.ts

sonar.exclusions=**/node*modules/**,**/coverage/**,**/outpu*/**
sonar.sourceEncoding=UTF-8

so*ar.javascript.lcov.reportPaths=cov*rage/lcov.info